---
- name: Install apache
  become: true
  ansible.builtin.yum:
    name: "httpd"
    state: present

- name: Install git
  become: true
  ansible.builtin.yum:
    name: "git"
    state: present

- name: clone a repo
  become: true
  ansible.builtin.git:
    repo: https://github.com/nbomasi/tooling-1.git
    #dest: /var/www/html
    dest: /var/www
    force: yes

- name: copy html content to one level up
  become: true
  command: cp -r /var/www/tooling-1/html /var/www/

- name: Start service httpd, if not started
  become: true
  ansible.builtin.service:
    name: httpd
    state: started

- name: recursively remove /var/www/html directory
  become: true
  ansible.builtin.file:
    path: /var/www/html
    state: absent